@base_url = http://localhost:3000

POST http://localhost:3000/search/update 

###
POST http://localhost:3000/search/update 
Content-Type: application/json

{
    "indexName":20
}

###
POST http://localhost:3000/api/embed 
Content-Type: application/json

{
    "indexName":20,
    "question": "What is the status of my order?",
    "answer": "Your order is in transit. It will be delivered by 5pm today."
}

###
POST http://localhost:3000/api/json
Content-Type: application/json

[{
"indexName":21,
"question": "Where is my order?",
"answer": "Your food is on the way. It will be delivered by 5pm today."
},{
"indexName":20,
"question": "Where is job?",
"answer": "your job is waiting for you."
},{
"indexName":20,
"question": "Where is my food?",
"answer": "Your food is in the kitchen."
},{
"indexName":20,
"question": "Where is my Key?",
"answer": "Your food is in the bedroom."
}]


###
DELETE http://localhost:3000/api/delete
Content-Type: application/json

{
    "indexName":20,
    "question":"Where is my Key?"
}

###
GET http://localhost:3000/api/match?sentence=hello%3F&indexName=20&neighbors=3
Content-Type: application/json

# {
#     "indexName":20,
#     "sentence":"Where is my Key?"
# }


### Get Session List
GET {{base_url}}/api/session/bb305a12-533a-457a-b963-ea6f3b6394e1

### Get Session Data
GET {{base_url}}/api/session/bb305a12-533a-457a-b963-ea6f3b6394e1/cbb0e2d0-925b-4027-8344-a1b9a3a421b1

### Save Session
POST {{base_url}}/api/session/bb305a12-533a-457a-b963-ea6f3b6394e1
Content-Type: application/json

{
  "data": {
    "example": "data"
  },
  "sessionName": "Example Session"
}

### Update Session Data
PUT {{base_url}}/api/session/bb305a12-533a-457a-b963-ea6f3b6394e1/cbb0e2d0-925b-4027-8344-a1b9a3a421b1
Content-Type: application/json

{
  "data": {
    "updated": "data"
  }
}

### Update Session Name
PUT {{base_url}}/api/session/bb305a12-533a-457a-b963-ea6f3b6394e1/cbb0e2d0-925b-4027-8344-a1b9a3a421b1/name
Content-Type: application/json

{
  "sessionName": "Name Updated"
}

### Delete Session
DELETE {{base_url}}/api/session/bb305a12-533a-457a-b963-ea6f3b6394e1/1cb7925a-e3da-4887-9049-1c08333c5ef1

@deploy_url = https://sherlock-inmemorysearch-production.up.railway.app
@user_id = bb305a12
@chat_id = f54415b1-5d06-487d-9c93-4afeeb5ffcfc
###
### GET /api/chat/:userId
###

GET {{base_url}}/api/chat/{{user_id}}

###

###
### GET /api/chat/:userId/:chatId
###

GET {{base_url}}/api/chat/{{user_id}}/{{chat_id}}

###

###
### POST /api/chat/:userId
###

POST {{base_url}}/api/chat/{{user_id}}
Content-Type: application/json

{
  "from": "2023-01-01",
  "to": "2023-01-10",
  "chatName": "Sample Chat"
}

###

###
### PUT /api/chat/:userId/:chatId
###

PUT {{base_url}}/api/chat/{{user_id}}/{{chat_id}}
Content-Type: application/json

{
  "isIn": true,
  "text": "Hello!"
}

###

###
### PUT /api/chat/:userId/:chatId/name
###

PUT {{base_url}}/api/chat/{{user_id}}/{{chat_id}}/name
Content-Type: application/json

{
  "chatName": "Updated Chat Name"
}

###

###
### DELETE /api/chat/:userId/:chatId
###

DELETE {{base_url}}/api/chat/{{user_id}}/{{chat_id}}

###

@org_id = spiderman128
@filter_id = d49be3a2-dac8-496b-98d8-ad3df59307b6
@stat_id = 447426d7-5040-4991-8698-0d18265b496c

###
### Filter 
###
GET  {{deploy_url}}/api/filter/{{user_id}}
Content-Type: application/json

####

POST {{deploy_url}}/api/filter/{{user_id}}
Content-Type: application/json

{
  "title": "New Filter 1",
  "options": ["stat1","stat2"]
}

####

DELETE {{deploy_url}}/api/filter/{{user_id}}/{{filter_id}}
Content-Type: application/json

###
### Stat
###

GET {{deploy_url}}/api/stat/{{org_id}}/list
Content-Type: application/json



###
### GET /api/stat/:orgId
###

# Request Parameters
@orgId = spiderman128
@startDate = 2023-07-24
@endDate = 2023-07-24

GET {{base_url}}/api/stat/{{orgId}}?startDate={{startDate}}&endDate={{endDate}}
Content-Type: application/json


###
### POST /api/stat/:orgId
###

POST {{deploy_url}}/api/stat/{{org_id}}
Content-Type: application/json

{
  "title": "New Stat Item",
  "category": "Paid Ads",
  "formatter": "fixedDecimalPointsFormatter"
}

###
### PUT /api/stat/:statId/name
###

PUT {{deploy_url}}/api/stat/name/{{org_id}}/{{stat_id}}
Content-Type: application/json

{
  "value": "Robo Stat Item"
}

###

PUT {{deploy_url}}/api/stat/formatter/{{org_id}}/{{stat_id}}
Content-Type: application/json

{
  "value": "dollarFormatter"
}

###
### PUT /api/stat/:orgId/:statId/value
###

PUT {{base_url}}/api/stat/{{org_id}}/{{stat_id}}/value
Content-Type: application/json

{
  "value": 101,
  "date": "2023-07-24"
}

###
### DELETE /api/stat/:orgId/:statId
###

POST {{base_url}}/api/stat/{{org_id}}/delete
Content-Type: application/json

{
  "statIds": ["86488343-5d67-49c1-8f7a-92cca12258d7"]
}
